&tl62      sheet:  2.   &bi12 HELP PAGE instructions

             4.   &bi14 COMMAND descriptions

             5.   &bi15 ASSIGNMENT descriptions

             6.   &bi16 DISPLAY PAGE selection

             6.   &bi16 USER NAME assignment

             7.   &bi17 SYSTEM FUNCTION index

             8.   &bi18 LOAD/SAVE voice or instrument files


 For HELP , touch any BOX with LIGHTPEN or TYPE: n<set>
                                        where: n = sheet no.

 For HELP with HELP PAGES , press <add> key.
&NS&TL12 A HELP PAGE  accompanies each standard DISPLAY PAGE, with full
 guidance for the use of the various features provided. A
 "screen-full" of help is called a SHEET - each help page
 consists of several of these sheets.&ls15
 A HELP INDEX  is provided on the FIRST sheet of every help page&ls10
 to allow quick access to HELP for major features in two ways:&ls15
   1. BY TYPING the sheet number and pressing <set> key.
   2. BY TOUCHING an illuminated INDEX BOX with the LIGHTPEN&ls10
       ("Touch" means: point pen at item without touching tip
         with finger then "trigger" by a quick touch on tip.)&ls15
 These INDEX BOXES are also provided  throughout  the HELP page.&ls10
 Any word inside an illuminated box may be touched with the 
 lightpen for help on that topic. See &bi13 PREVIOUS SHEET BOX.&ls15
 TO CHANGE HELP SHEETS   
   PRESS :  <add> key        TO : go forward to next sheet&ls10
          <sub>               go backward to preceding sheet
          <set>               go to 1st sheet (HELP INDEX)
     (sheet no.)<set>         go to any sheet; e.g. 3<set>
   <clear>  or  <return>      return to DISPLAY PAGE&ls15
                 press <add> key for next sheet&ls10
&NS TO CHANGE HELP SHEETS with LIGHTPEN  five "touchable" boxes 
 are provided at the top of each sheet as well as the INDEX
 BOXES placed around key words.&ls15
   TOUCH :  <FWD> box       TO : go forward to next sheet&ls10
          <BWD>              go backward to preceding sheet
          <TOP>              go to 1st sheet - HELP INDEX
          <PRE>              go to  previous sheet
          <PAGE x>           return to DISPLAY PAGE
        <INDEX BOX>          select sheet for illuminated word&ls15
 THE PREVIOUS SHEET BOX :<PRE> is related to the illuminated INDEX&ls10
 boxes found around key words. When an INDEX box is touched
 with the lightpen, the sheet for that topic will be selected. 
 Touching <PRE> will then take you back to the original 
 (previous) sheet. In fact you can backtrack through consecutive
 INDEX box touches in this way; each touch of <PRE> will take 
 you back one further previous sheet. Thus the HELP sheets can 
 be easily browsed with the LIGHTPEN without losing your place.&ls15
 ALL COMMANDS  provided by the DISPLAY PAGE shown at upper-left&ls10
 may be typed WHILE the HELP page is selected. Simply type the 
 command as described by the HELP sheet. You will exit back to 
 the display page automatically.&ls15
                 press <add> key for next sheet&ls10
&NS CONCISE DESCRIPTIONS  of what you are to TYPE or touch with&ls10
 the LIGHTPEN to use the DISPLAY PAGES are presented with the 
 aid of a few symbolic conventions.
    Special Keys  are indicated with lower-case letters within
    "<>" brackets: <return>,<set>,<add>,<sub>,<clear>,etc.
    Lightpen Items  are indicated with upper-case letters within
    "<>" brackets: <FWD>,<BWD>,<TOP>,etc.
    Items which are defined when typed  are indicated with &ls10
    lower-case letters (see "n" && "s" in the following example).&ls15
 COMMANDS  tell the CMI to "do something". The <return> key is&ls10
 always the last key typed. Commands are described like this....&ls15
 TO SELECT a HELP PAGE                       TYPE:&ls10
   select HELP for current DISPLAY page  -  H<return>
   select HELP for DISPLAY page (n)      -  Hn<return>
   select HELP for page (n), SHEET (s)   -  Hn,s<return>&ls15
       where:  n  =  name (number or letter) of page: 1-9,D,L&ls10
               s  =  sheet number&ls15
   EXAMPLES:  H2<return>   Select PAGE 2 HELP (sheet 1)&ls10
              HD,2<return> Select PAGE D HELP, sheet 2&ls15
  This command may be given from either a DISPLAY or HELP page.
                 press <add> key for next sheet&ls10
&NS ASSIGNMENTS  change the values, or "settings" of variable 
 parameters.  The <set> key is usually the last key typed.
 Assignments are described like this example from PAGE 3....&ls15
 To SET MASTER PITCH  use <arrow> keys or LIGHTPEN to TAB to PITCH&ls10
    TYPE: n<set>
   where: n  = desired tuning, 0 - 255&ls15
 Because the value is a number we call this a NUMERIC assignment&ls10
 (as opposed to ALPHABETIC where the value is a word or name).
 When making ANY NUMERIC ASSIGNMENT  the <add> or <sub> keys can&ls10 
 be used instead of <set> to ADD or SUBTRACT the typed number
 from the current value. The use of these keys is up to you; 
 thus they are not often mentioned but are always available.&ls15   
 TABBING to an ITEM  means to SELECT it for an assignment. This &ls10
  can be done with either the 4 <arrow> keys or LIGHTPEN.     
         ARROW KEYS:  Press necessary keys to move the CURSOR
                        (illuminated box) to the desired item.
           LIGHTPEN:  Touch displayed value of item.&ls15
 THE COMMAND LINE is NOT CLEARED  after a COMMAND ERROR or any&ls10 
 ASSIGNMENT. The NEXT key typed will automatically clear the 
 command line  UNLESS  it is one of the following keys:
         <rubout> <arrow> <home> <add> <sub> <set>
                 press <add> key for next sheet
&NS TO SELECT A DISPLAY PAGE    
   TYPE:    Pn<return> 
   where:    n  =  fill in the number or letter of desired page.
       <return> =  the RETURN key

 EXAMPLE:   P2<return>   (select DISPLAY PAGE 2)

 On PAGE 1 the LIGHTPEN may be used to select any other page by
 touching the page name or title.  On other pages, touching the
 word INDEX (at upper left) will re-select PAGE 1.

 TO SET USER NAME ON SYSTEM DISK
  First, use <down-arrow> key to TAB (move illuminated cursor)
  to USER NAME.
    TYPE:   up to 20 characters<set>
    where:  <set> = the SET key.

 SYSTEM FUNCTION INDEX
 The next sheet is a index of SYSTEM FUNCTIONS and the DISPLAY 
 PAGES on which they are provided.  Wherever a function is 
 found on more than one page, parentheses indicate the HELP page
 with the most comprehensive description.
                 press <add> key for next sheet&ls10
&NS&LS9 KEYBOARD / REGISTER CONTROL              DISPLAY (help) PAGES :
           Keyboard Number selection  1 2(3)4 5 6 7 8 9 D L C
  Nphony control / Register creation  . . 3 . . . . . . . . .
        Register-to-Keyboard mapping  . . 3 . . . . . . . . .
                              Tuning  . . 3 . . . . . . . . .
 VOICE CONTROL                        
         Harmonic Waveform Synthesis  . . .(4)5 . . . . . . .
      Video-graphic Waveform Drawing  . . . . . 6 . . . . . .
    External Audio Waveform Sampling  . . . . . . . 8 . . . .
              Display Voice waveform  . . . . 5 6 . . . D . .
                                Mode  . . 3 . . .(7). . . . .
                                Loop  . . .(4). . 7 . . . . .
                           Amplitude  . . . 4 . 6(7). . . . .
      Vibrato / Glide / Key velocity  . . . . . . 7 . . . . .
        Keyboard Controls && Switches  . . . . . . 7 . . . . .
 SEQUENCER CONTROL                    
  Record / Replay Keyboard Sequences  . . . . . . . . 9 . . .
  Create / Edit / Replay M.C.L files  . . . . . . . . . . . C
 DISK CONTROL                          
          Display / Change Filenames  . 2 . . . . . . . . . .
Load / Save Voice or Instrument file  1 2(3)4 5 6 . 8 . D L .
            Load / Save Control file  . . . . . . 7 . . . . .
        Load Keyboard Sequence files  1 2 3 4 5 6 . 8(9)D L .
  Load files by Keypad on master kbd  1(2)3 4 5 6 7 8 9 D L C
        Free Space remaining on disk  .(2). . . . . . 9 . . .
             Delete / Transfer files  . 2 . . . . . . . . . .
                        Disk Library  . . . . . . . . . . L .
&NS&TL12&LS10 TO LOAD/SAVE VOICES or INSTRUMENTS   TYPE:
       To LOAD a VOICE         -   L,r,filename<return>
       To SAVE a VOICE         -   S,filename<return>
       To CREATE a VOICE       -   C,r,filename<return>
       To LOAD an INSTRUMENT   -   L,filename.IN<return>
       To SAVE an INSTRUMENT   -   S,filename.IN<return>

        where:     r  =  register A - H 
            filename  =  1-8 character filename 

 EXAMPLES:  
   L,LUCK.IN<return>  Load instrument file LUCK
   L,A,FUZZ<return>   Load voice file FUZZ into register A
   C,A,NEWV<return>   Create voice NEWV in register A
   
 These commands may be given from ALL standard DISPLAY PAGES
 except PAGE 9.  See PAGE 3 HELP for more about VOICES,
 INSTRUMENTS, and LOADING/SAVING files. See PAGE 2 HELP to
 LOAD files with LIGHTPEN.




                 end - press <set> for 1st sheet
                                                            